
library(shiny)
shinyUI(navbarPage("Diamond Price Analysis",
                        tabPanel("Documentation",
                                 h2("Diamond Price Analysis"),
                                 div("The Diamond Price Analysis Application provides 
                                            a tool to perform general exploratory analysis on 
                                            the diamonds dataset."),
                                 br(),
                                 div("In addition to the exploratory tools, the application also offers 
                                            the user the opportunity to see how the predicted 
                                            price of a diamond is affected by different linear
                                            models of the data."),
                                 h3("Exploratory Analysis"),
                                 div("The Exloratory Analysis provides a visual 
                                            representation of the linear relationship between
                                            the price of a diamond and the number of carats.
                                            The user can manipulate the third dimension, the
                                            color of the points, by choosing from the 
                                            appropriate dropdown. The user can also choose
                                            to include a fitted line to the data by checking
                                            the appropriate box."),
                                 br(),
                                 div("The linear model is 
                                            accompanied by various visualizations of the 
                                            price per cut as compared to the other variables.
                                            The size of the shapes in each graphic is governed
                                            by the carat variable, and the user can control 
                                            the fourth dimension, the color of the points, 
                                            by choosing from the appropriate dropdown."),
                                 h3("Price Predictions"),
                                 div("The Price Predictions allows the user to input 
                                            the parameters for various variables associated 
                                            to the diamonds dataset. By manipulating the 
                                            inputs, the user can then view the predicted 
                                            price as generated by several deifferent models 
                                            of the data.")
                                 ),
                        tabPanel("Exploratory Analysis",
                                fluidPage(
                                        fluidRow(
                                                column(6,
                                                       "Exploratory Analysis",
                                                       selectInput("selectedPointColor",
                                                                   "Select Color of Points",
                                                                   choices = c("Color", "Cut", "Clarity", "Size", "Carat")),
                                                       checkboxInput("showFittedLine", "Show Fitted Line", 
                                                                     value = FALSE),
                                                       submitButton("Submit")),
                                                column(6,
                                                       "Scatterplot",
                                                       plotOutput("scatterPlot")
                                                       )
                                                ),
                                        fluidRow(column(6,
                                                        "Price by Cut",
                                                        plotOutput("cutPricePlot")
                                                        ),
                                                 column(6,
                                                        "Price by Color",
                                                        plotOutput("colorPricePlot"))
                                                 ),
                                        fluidRow(column(6,
                                                        "Price by Clarity",
                                                        plotOutput("clarityPricePlot")
                                                        ),
                                                 column(6,
                                                        "Price by Size",
                                                        plotOutput("sizePricePlot"))
                                                 )
                                        )
                                ),
                        tabPanel("Price Predictions",
                                 sidebarPanel(
                                         sliderInput("sliderCarat", 
                                                     "How many carats is the diamond?",
                                                     1,
                                                     4.5,
                                                     value = 1),
                                         selectInput("selectedCut", "Select Cut", 
                                                     choices = unique(as.character(df$cut))),
                                         selectInput("selectedColor", "Select Color",
                                                     choices = unique(as.character(df$color))),
                                         selectInput("selectedClarity", "Select Clarity",
                                                     choices = unique(as.character(df$clarity))),
                                         submitButton("Submit")),
                                 mainPanel(
                                         h4("Predicted Price from Model: Price ~ Carats + Color"),
                                         textOutput("predColor"),
                                         h4("Predicted Price from Model: Price ~ Carats + Clarity"),
                                         textOutput("predClarity"),
                                         h4("Predicted Price from Model: Price ~ Carats + Cut"),
                                         textOutput("predCut"),
                                         h4("Predicted Price from Model: Price ~ Carats + Color + Clarity + Cut"),
                                         textOutput("predAll"))
                        )
))